### ISSUE TITLE
compile failing on raft branch on newton

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#4249]
I am getting the following error while compiling on newton. I am configured to use `GCC 4.6.3`. The output is:

```
In file included from src/clustering/table_manager/table_manager.cc:5:0:
./src/clustering/generic/raft_core.tcc: In lambda function:
./src/clustering/generic/raft_core.tcc:828:33:   instantiated from ‘raft_member_t<state2_t>::on_connected_members_change(const raft_member_id_t&, const boost::optional<long unsigned int>*) [with state_t = table_raft_state_t]::<lambda()>’
./src/clustering/generic/raft_core.tcc:827:9:   instantiated from ‘void raft_member_t<state2_t>::on_connected_members_change(const raft_member_id_t&, const boost::optional<long unsigned int>*) [with state_t = table_raft_state_t]’
./src/clustering/generic/raft_core.tcc:98:14:   instantiated from ‘raft_member_t<state2_t>::raft_member_t(const raft_member_id_t&, raft_storage_interface_t<state_t>*, raft_network_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]’
./src/clustering/generic/raft_network.tcc:25:68:   instantiated from ‘raft_networked_member_t<state_t>::raft_networked_member_t(const raft_member_id_t&, mailbox_manager_t*, watchable_map_t<raft_member_id_t, raft_business_card_t<state_t> >*, raft_storage_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]’
src/clustering/table_manager/table_manager.cc:69:84:   instantiated from here
./src/clustering/generic/raft_core.tcc:831:22: error: ‘check_invariants’ was not declared in this scope
./src/clustering/generic/raft_core.tcc:833:17: error: ‘on_rpc_from_leader’ was not declared in this scope
In file included from src/clustering/table_manager/table_manager.cc:5:0:
./src/clustering/generic/raft_core.tcc:842:26: error: ‘check_invariants’ was not declared in this scope
./src/clustering/generic/raft_core.tcc:828:33:   instantiated from ‘raft_member_t<state2_t>::on_connected_members_change(const raft_member_id_t&, const boost::optional<long unsigned int>*) [with state_t = table_raft_state_t]::<lambda()>’
./src/clustering/generic/raft_core.tcc:827:9:   instantiated from ‘void raft_member_t<state2_t>::on_connected_members_change(const raft_member_id_t&, const boost::optional<long unsigned int>*) [with state_t = table_raft_state_t]’
./src/clustering/generic/raft_core.tcc:98:14:   instantiated from ‘raft_member_t<state2_t>::raft_member_t(const raft_member_id_t&, raft_storage_interface_t<state_t>*, raft_network_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]’
./src/clustering/generic/raft_network.tcc:25:68:   instantiated from ‘raft_networked_member_t<state_t>::raft_networked_member_t(const raft_member_id_t&, mailbox_manager_t*, watchable_map_t<raft_member_id_t, raft_business_card_t<state_t> >*, raft_storage_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]’
src/clustering/table_manager/table_manager.cc:69:84:   instantiated from here
./src/clustering/generic/raft_core.tcc:855:22: error: ‘check_invariants’ was not declared in this scope
In file included from src/clustering/table_manager/table_manager.cc:5:0:
./src/clustering/generic/raft_core.tcc: In lambda function:
./src/clustering/generic/raft_core.tcc:969:44:   instantiated from ‘raft_member_t<state2_t>::on_watchdog_timer() [with state_t = table_raft_state_t]::<lambda()>’
./src/clustering/generic/raft_core.tcc:969:9:   instantiated from ‘void raft_member_t<state2_t>::on_watchdog_timer() [with state_t = table_raft_state_t]’
./src/clustering/generic/raft_core.tcc:92:20:   instantiated from ‘raft_member_t<state2_t>::raft_member_t(const raft_member_id_t&, raft_storage_interface_t<state_t>*, raft_network_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]::<lambda()>’
./src/clustering/generic/raft_core.tcc:92:10:   instantiated from ‘raft_member_t<state2_t>::raft_member_t(const raft_member_id_t&, raft_storage_interface_t<state_t>*, raft_network_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]::<lambda()>’
./src/clustering/generic/raft_core.tcc:98:14:   instantiated from ‘raft_member_t<state2_t>::raft_member_t(const raft_member_id_t&, raft_storage_interface_t<state_t>*, raft_network_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]’
./src/clustering/generic/raft_network.tcc:25:68:   instantiated from ‘raft_networked_member_t<state_t>::raft_networked_member_t(const raft_member_id_t&, mailbox_manager_t*, watchable_map_t<raft_member_id_t, raft_business_card_t<state_t> >*, raft_storage_interface_t<state_t>*, const raft_persistent_state_t<state_t>&, const string&) [with state_t = table_raft_state_t, std::string = std::basic_string<char>]’
src/clustering/table_manager/table_manager.cc:69:84:   instantiated from here
./src/clustering/generic/raft_core.tcc:980:82: error: ‘effective_last_heard_from_leader’ was not declared in this scope
```

`git bisect` places the problem in c97068c6352b54f8435e886cb5f262951791f473

**Comment by timmaxw** [comment]
@Tryneus has already fixed this in his branch.

**Comment by Tryneus** [comment]
The fix for this (and release build of the unittests) is up in review 2904.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `raft` in commit d481fb7.
