### ISSUE TITLE
compiling v1.13.x and next broken with error on newton

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#2632]
Building the current HEAD of both `next` and `v1.13.x` is currently broken with the message:

```
./src/containers/archive/versioned.hpp: In function ‘void deserialize_sindex_info(const std::vector<char>&, ql::map_wire_func_t*, sindex_multi_bool_t*)’:
./src/containers/archive/versioned.hpp:56:5: error: ‘cluster_version’ may be used uninitialized in this function [-Werror=uninitialized]
src/rdb_protocol/btree.cc:1095:23: note: ‘cluster_version’ was declared here
```

A little trial, and it looks like the error was introduced with commit 5942e53 on `v1.13.x` (Bump cluster version to 1.13.2. Differentiate between cluster version and disk version instantiation.), and is probably the congruent checkin on `next`.
