### ISSUE TITLE
Build on CentOS 6.5

### ISSUE THREAD

**Issue by mdmdmdmd** [rethinkdb/rethinkdb#3431]
Hello ya'all:

gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)

./configure --prefix /rethinkdb --sysconfdir /rethinkdb/conf --localstatedir /rethinkdb/data --static none --allow-fetch

Here is the make output:

   [138/380] CC build/release_clang/obj/protob/protob.o
    [139/380] CC build/release_clang/obj/protob/json_shim.o
src/protob/json_shim.cc:190:38: error: no type named 'FatalException' in namespace 'google::protobuf'
    } catch (const google::protobuf::FatalException &) {
                   ~~~~~~~~~~~~~~~~~~^
1 error generated.
make[1]: **\* [build/release_clang/obj/protob/json_shim.o] Error 1
make: **\* [make] Error 2

cheers, 

marco
