### ISSUE TITLE
build issue on MacOS in src/rdb_protocol/changefeed.cc

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#5017]
I am getting a build issue on MacOS (both locally on 10.11, and on gantz which is on 10.10.5), but is not reproducing on `newton` even with Clang3.5. Bisecting puts this as having introduced in 4e0c48d9, so assigning to @mlucy 

```
src/rdb_protocol/changefeed.cc:1547:9: error: no matching member function for call to 'each_sub_in_vec'
        each_sub_in_vec<range_sub_t>(range_subs, &spot, lock, f);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/rdb_protocol/changefeed.cc:1393:10: note: candidate function [with Sub = ql::changefeed::range_sub_t] not viable: no known conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'const std::function<void (range_sub_t *)>' for 4th argument
    void each_sub_in_vec(
         ^
src/rdb_protocol/changefeed.cc:1556:41: error: no viable conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'const std::function<void (point_sub_t *)>'
        each_point_sub_with_lock(&spot, f);
                                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1485:5: note: candidate constructor not viable: no known conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'nullptr_t' for 1st argument
    function(nullptr_t) noexcept : __f_(0) {}
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1486:5: note: candidate constructor not viable: no known conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'const std::__1::function<void (ql::changefeed::point_sub_t *)> &' for 1st argument
    function(const function&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1487:5: note: candidate constructor not viable: no known conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'std::__1::function<void (ql::changefeed::point_sub_t *)> &&' for 1st argument
    function(function&&) noexcept;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1491:41: note: candidate template ignored: disabled by 'enable_if' [with _Fp = std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>]
                                        __callable<_Fp>::value &&
                                        ^
src/rdb_protocol/changefeed.cc:1406:51: note: passing argument to parameter 'f' here
        const std::function<void(point_sub_t *)> &f) throw ();
                                                  ^
src/rdb_protocol/changefeed.cc:1567:41: error: no viable conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'const std::function<void (limit_sub_t *)>'
        each_limit_sub_with_lock(&spot, f);
                                        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1485:5: note: candidate constructor not viable: no known conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'nullptr_t' for 1st argument
    function(nullptr_t) noexcept : __f_(0) {}
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1486:5: note: candidate constructor not viable: no known conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'const std::__1::function<void (ql::changefeed::limit_sub_t *)> &' for 1st argument
    function(const function&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1487:5: note: candidate constructor not viable: no known conversion from 'std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>' to 'std::__1::function<void (ql::changefeed::limit_sub_t *)> &&' for 1st argument
    function(function&&) noexcept;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1491:41: note: candidate template ignored: disabled by 'enable_if' [with _Fp = std::__1::__bind<void (ql::changefeed::subscription_t::*)(std::exception_ptr, ql::changefeed::detach_t), std::__1::placeholders::__ph<1> &, std::exception_ptr, ql::changefeed::detach_t>]
                                        __callable<_Fp>::value &&
                                        ^
src/rdb_protocol/changefeed.cc:1410:51: note: passing argument to parameter 'f' here
        const std::function<void(limit_sub_t *)> &f) throw ();
                                                  ^
3 errors generated.
```

**Comment by larkost** [comment]
@mlucy is this one going to get attention soon? We are unable to test on MacOS at the moment.

**Comment by danielmewes** [comment]
I'm going to take a look at this, since @mlucy is busy wrapping up #4343.

**Comment by danielmewes** [comment]
Fix in branch `daniel_5017` and CR 3306.

**Comment by danielmewes** [comment]
Fixed in `next` 0a500e73a2ca3cddc81f8e963a76bbed2ae57e3d
