### ISSUE TITLE
next build broken on MacOS in src/arch/io/disk/pool.cc

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#3102]
Building `next` is currently broken on MacOS (clang) as of 7f2c8d4 (according to `git bisect`). It is working fine on gcc (e.g.: newton). The exact message is:

``` c++
src/arch/io/disk/pool.cc:90:16: error: use of undeclared identifier 'off_part'
    do { if (!(off_part == 0)) { do { report_fatal_error("src/arch/io/disk/pool.cc", 90, "Guarantee" " failed: [" "off_part == 0" "] "); (raise(5)); } while (0); } } while (0);
               ^
```

Since this checkin was made by @Tryneus I will start this off with him.
