### ISSUE TITLE
Build Error 2.0.4 on Centos 6.5 x64

### ISSUE THREAD

**Issue by mdmdmdmd** [rethinkdb/rethinkdb#4614]
Executed the following commands on FRESH Centos 6.5 install:

To Build in Centos 6.5:

rpm --import http://ftp.scientificlinux.org/linux/scientific/5x/x86_64/RPM-GPG-KEYs/RPM-GPG-KEY-cern

wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo

sudo yum install devtoolset-2 ncurses-devel boost-static openssl-devel libcurl-devel wget tar which m4

#To make it build faster				
rpm -Uvh http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm

sudo yum install protobuf-devel jemalloc-devel

Now Change to the Rethink2.xx directory

wget http://download.rethinkdb.com/dist/rethinkdb-2.0.4.tgz
#tar xf rethinkdb-2.0.4.tgz

scl enable devtoolset-2 -- ./configure --dynamic jemalloc --allow-fetch

scl enable devtoolset-2 -- make

################BUILD RESULT BELOW- ERRORS##################

[root@localhost rethinkdb204]# scl enable devtoolset-2 -- make
    [1/336] CC build/release/obj/protob/json_shim.o
src/protob/json_shim.cc: In function ‘bool json_shim::parse_json_pb(Query*, int64_t, const char*)’:
src/protob/json_shim.cc:190:53: error: expected unqualified-id before ‘&’ token
     } catch (const google::protobuf::FatalException &) {
                                                     ^
src/protob/json_shim.cc:190:53: error: expected ‘)’ before ‘&’ token
src/protob/json_shim.cc:190:53: error: expected ‘{’ before ‘&’ token
src/protob/json_shim.cc:190:54: error: expected primary-expression before ‘)’ token
     } catch (const google::protobuf::FatalException &) {
                                                      ^
src/protob/json_shim.cc:190:54: error: expected ‘;’ before ‘)’ token
src/protob/json_shim.cc:192:7: error: expected primary-expression before ‘catch’
     } catch (...) {
       ^
src/protob/json_shim.cc:192:7: error: expected ‘;’ before ‘catch’
make[1]: *** [build/release/obj/protob/json_shim.o] Error 1
make: *** [make] Error 2
[root@localhost rethinkdb204]#

**Comment by AtnNn** [comment]
It looks like you may have an unsupported protobuf version, possibly too old or too young, or that some files were built with one version, and others with another.

What version of `protobuf-devel` do you have installed?

Did you start building, change the version of protobuf being used, and then rebuild?

Do you get the same errors if you run `make clean; scl enable devtoolset-2 -- make build/release/obj/protob/json_shim.o`?

**Comment by danielmewes** [comment]
@mdmdmdmd Have you had a chance to try @AtnNn's suggestions? Does the problem still persist?

**Comment by danielmewes** [comment]
Closing since we haven't have heard from @mdmdmdmd . @mdmdmdmd please let us know if this is still an issue.
