### ISSUE TITLE
Add Mac ARM build

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#6932]
It would be nice if ARM users could run RethinkDB natively.

Or even, if we could verify that the x86 build runs properly under emulation.

**Comment by v3ss0n** [comment]
I am thinking about building M1 Minis as servers (still waiting orders) so yes i would like to see if its work too. Any contributors with M1 Mini ?

**Comment by chrisvariety** [comment]
I have a M1 Mini, happy to help!

**Comment by v3ss0n** [comment]
Nice , would be cool if you can try :
- x86 binary 
- native ARM Built.
- Benchmarks

**Comment by srh** [comment]
That would be cool.

@chrisvariety I guess you could, uh, try it then!

I just tried it out on a quad-core ARM Ubuntu 20.04 system (the first time I did an actual ARM build, for what it's worth) and it built and ran, no problemo, with 4 GB of RAM, no swap space, and make -j6.  So, I'm glad to know the ARM stuff *generally* works.

I see one obvious problem in the packaging system:

```
mk/support/pkg/openssl.sh
16:    if [[ "$OS" = "Darwin" ]]; then
17-        in_dir "$build_dir" ./Configure darwin64-x86_64-cc -shared --prefix="$(niceabspath "$install_dir")" $CFLAGS
```

Maybe there are places in the source code with __MACH__ or __APPLE__ that ought to be checked out.  I don't see any obvious problems; the most suspicious place is in src/rethinkdb_backtrace.cc.

**Comment by chenrui333** [comment]
Good timing, we have a [arm build log](https://github.com/Homebrew/homebrew-core/runs/1613574220) on the homebrew side. (relates to https://github.com/Homebrew/homebrew-core/pull/67782)

**Comment by GeoffreyPlitt** [comment]
Is there any way to run rethinkdb on M1?

**Comment by srh** [comment]
@GeoffreyPlitt Macs on M1 can run native x86 binaries, can't they?

**Comment by GeoffreyPlitt** [comment]
There's a Rosetta emulation layer for user-space terminal stuff, but I
don't know how to make that work for daemons. Is there a way to run
rethinkdb as a static binary from the command-line, without daemonizing?

**Comment by NetOperatorWibby** [comment]
Dang.

I'm typing this on an M1 MBA and I was hoping there was some beta build of RethinkDB I could use.

I'll do some research and will report back if I find anything useful.

**Comment by NetOperatorWibby** [comment]
This is the output of `make` when building from scratch:

```
    [1/460] FETCH protobuf_2.5.0
    [2/460] INSTALL-INCLUDE protobuf_2.5.0
    [3/460] BUILD protobuf_2.5.0
./google/protobuf/stubs/atomicops_internals_macosx.h:162:50: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
inline Atomic64 Barrier_AtomicIncrement(volatile Atomic64* ptr,
                                                 ^~~~~~~~
                                                 Atomic32
./google/protobuf/stubs/atomicops.h:65:15: note: 'Atomic32' declared here
typedef int32 Atomic32;
              ^
In file included from google/protobuf/stubs/atomicops_internals_x86_gcc.cc:36:
In file included from ./google/protobuf/stubs/atomicops.h:173:
./google/protobuf/stubs/atomicops_internals_macosx.h:163:41: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
                                        Atomic64 increment) {
                                        ^~~~~~~~
                                        Atomic32
./google/protobuf/stubs/atomicops.h:65:15: note: 'Atomic32' declared here
typedef int32 Atomic32;
              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [atomicops_internals_x86_gcc.lo] Error 1
make[2]: *** [install-recursive] Error 1

Full error log: ./build/external/protobuf_2.5.0_install.log
make[1]: *** [build/external/protobuf_2.5.0/bin/protoc] Error 1
make: *** [make] Error 2
```

**Comment by GeoffreyPlitt** [comment]
Thanks for the update! I'm not great on C++ compiling, but if you make progress and post an update here, I'd be happy to test it out.

**Comment by NetOperatorWibby** [comment]
It seems like protobuf is still having issues building on M1 so at the very least, if that's not building consistently we're kinda SOL for a while.

**Comment by NetOperatorWibby** [comment]
I JUST REALIZED THE BINARY WORKS ON M1-BASED MACS

https://download.rethinkdb.com/repository/raw/osx/rethinkdb-2.4.1.dmg

Y'all, I cannot contain my excitement. I just spent a few miserable days trying to get used to CouchDB. I'm so glad I can retreat back to my love, my everything, my RethinkDB.

Hell yeah!

**Comment by GeoffreyPlitt** [comment]
Wow, worked for me too!

So I'm able to run the server by opening a new terminal and running "rethinkdb". But is there a way to have it run in background (daemon) and run on system startup? I'm used to the way "brew install rethinkdb" worked.

**Comment by NetOperatorWibby** [comment]
Hmm, that's a good question. You could definitely setup a script that just runs on launch in a minimized window but that's not the same.

**Comment by 462548187** [comment]
I also need to be able to run on Mac M1

**Comment by GeoffreyPlitt** [comment]
Hello ReThink team, can we get the working binary (above) repackaged/rereleased for Mac Homebrew for M1 machines?

**Comment by GeoffreyPlitt** [comment]
@NetOperatorWibby Any luck getting this to run on startup, and in the background? @chrisvariety @srh @v3ss0n any ideas? I'd love to get the "brew install rethinkdb" package fixed, if someone knows how to do that?

**Comment by ChauserMondieu** [comment]
I'm sorry if I'm re-invoking this issue, but I'm currently working on MacBkko Pro with Darwin20.0.0 OS, and the same problem occurred to me, which is 
./google/protobuf/stubs/atomicops_internals_macosx.h:162:50: error: unknown type name 'Atomic64'; did you mean 'Atomic32'?
Are there any solutions to this problem without me changing os? Thanks again.

**Comment by srh** [comment]
@ChauserMondieu Is the x86 binary not working for you?

A solution to that specific build problem might be for the google protobuf version we use (which is defined in the build system) to be upgraded.

**Comment by srh** [comment]
I've added upgrading dependency versions to #6975.

This issue is already explicitly on its list as well.

**Comment by GeoffreyPlitt** [comment]
Will this eventually install on ARM macs via homebrew? https://formulae.brew.sh/formula/rethinkdb#default

**Comment by srh** [comment]
I don't know.

**Comment by srh** [comment]
We have ARM builds working but not .dmg file building working.  This .dmg issue is partly ARM specific but it might also affect x86 dmg building.  (Some new versions of some of its dependencies, python3, etc, might be a factor.)
