### ISSUE TITLE
OSX build failure 1.15.0: no viable conversion to bool

### ISSUE THREAD

**Issue by kofalt** [rethinkdb/rethinkdb#3109]
On tag `v1.15.0` on commit `4d2fd72`, failed to build on OSX 10.9.5:

```
   [180/383] CC build/release_clang_notcmalloc/obj/clustering/reactor/reactor_be_primary.o
    [181/383] CC build/release_clang_notcmalloc/obj/clustering/reactor/reactor_be_secondary.o
src/clustering/reactor/reactor_be_primary.cc:293:12: error: no viable conversion from 'const
      boost::optional<broadcaster_business_card_t>' to 'bool'
    return maybe_a_business_card.get();
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    [182/383] CC build/release_clang_notcmalloc/obj/clustering/reactor/reactor_json_adapters.o
1 error generated.
make[1]: *** [build/release_clang_notcmalloc/obj/clustering/reactor/reactor_be_primary.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [make] Error 2
```

Full paste of the build log [here](http://hastebin.com/ebufipulep.pas).

```
./configure --allow-fetch
time nice make -j 4
```

```
Note: checking out '4d2fd72'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 4d2fd72... Bump driver version numbers to 1.15.0.0
* Detecting system configuration
Bash:                           4.3.27(1)-release
Use ccache:                     no
C++ Compiler:                   CLANG 6.0 (/usr/bin/c++)
Host System:                    x86_64-apple-darwin13.4.0
Build System:                   Darwin 13.4.0 x86_64
Cross-compiling:                no
Host Operating System:          Darwin
Without tcmalloc:               yes
Build Architecture:             x86_64
stdlib:                         -lc++
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              external/protobuf_2.5.0
python:                         python 2.7.5
Node.js package manager:        /usr/local/bin/npm
LESS css:                       external/less_1.6.2
CoffeeScript:                   external/coffee-script_1.7.1
Handlebars:                     external/handlebars_1.3.0
Browserify:                     external/browserify_3.24.13
bluebird:                       external/bluebird_1.2.1
wget:                           /usr/local/bin/wget
curl:                           /usr/bin/curl
Google Test:                    external/gtest_1.6.0
termcap:                        -ltermcap
boost_system:                   -lboost_system
ssl:                            -lssl
Protobuf library:               external/protobuf_2.5.0
v8:                             external/v8_3.22.24.17
RE2:                            external/re2_20140111
z:                              -lz
crypto:                         -lcrypto
curl:                           -lcurl
Test protobuf:                  external/protobuf_2.5.0
Test boost:                     ok
Installation prefix:            /usr/local
Configuration prefix:           /usr/local/etc
Runtime data prefix:            /usr/local/var
* Wrote configuration to config.mk
```
