### ISSUE TITLE
Python driver SSL only works with Python 3.2+

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#4815]
In Python 2.7, I'm getting
```
rethinkdb.errors.ReqlDriverError: Could not connect to aws-us-east-1-portal.3.dblayer.com:10575. Error: 'module' object has no attribute 'SSLContext'
```
when trying to connect through SSL.

The problem I think is that `ssl.SSLContext` was only added in Python 3.2, see https://docs.python.org/dev/library/ssl.html#ssl.SSLContext

**Comment by danielmewes** [comment]
Maybe we could use `backports.ssl`? https://pypi.python.org/pypi/backports.ssl/0.0.7

**Comment by nighelles** [comment]
I ran into this earlier, I think SSLContext is in 2.7.9 as well.

**Comment by danielmewes** [comment]
More people are now encountering this when running the import/export scripts against a TLS-enabled cluster.

@larkost could you take a look at this?

**Comment by larkost** [comment]
Looking over the code it seems we are using `ssl.SSLContext` for 2 things that we can't get from the normal `ssl.wrap_socket` method:
- disallowing `SSLv2` and `SSLv3`
- setting the `check_hostname` attribute to `True`

Both of these are valid security improvements, and certainly we should use them when available, but I wonder if we should make them requirements. Given that question I see three routes to fixing this:
1. Try to use `backports.ssl` as mentioned, but reading their [issues](https://github.com/alekstorm/backports.ssl/issues) does make me worry a bit about chasing bugs.
2. Stop trying to set those two options (BOOO, HISS)
3. Check to see if `SSLContext` is present, and set those options if it is, otherwise preceded without them.

And as a side note: we are currently not using `SSLContext` as it is supposed to be used: that is as a reusable context for multiple connections. I will fix this in the code regardless of the route we decide to take.

@danielmewes: any opinions on the route we want to take?

**Comment by danielmewes** [comment]
I don't think `check_hostname` is very important for us, since most users will use their own private certificate for verifying the server certificate, rather than using a certificate signed by a public CA.

Especially if the server certificate is self-signed, an attacker who gets access to the matching private key could sign their own certificates for arbitrary host names anyway.

I think we also don't verify the hostname in the other drivers, though I could be wrong.

Disallowing `SSLv2` and `SSLv3` on the other hand sounds like a good idea.

I think that it's probably fine to go for option 3 and not set these options if `SSLContext` is not available. I'd like to hear @VeXocide's opinion though.

**Comment by VeXocide** [comment]
Since we disable `SSLv2`, `SSLv3`, `TLSv1`, and `TLSv1.1` on the server side, as well as enforcing `SSL_OP_CIPHER_SERVER_PREFERENCE`, there's no strict need to disallow this on the client side.

I'd like to keep the `check_hostname` and have it on by default, but allow the user to disable it if needed for the reasons @danielmewes mentioned.

**Comment by larkost** [comment]
@VeXocide: for clarity, this would not be something that the user would be disabling, except by their (OS's) choice of Python version. And it is not something we probably would be advertising (except maybe in documentation).

And again, for clarity, even if we are disallowing those options on the server, if they are options on the client then there is a chance for someone to man-in-the-middle if we go with options 2 or 3.

All that being said I am still for option 3. Unless anyone disagrees, I will go with that option.

**Comment by larkost** [comment]
I should also mention that for those users who are interested in the more secure behavior on Python versions that don't support it natively they could import `backports.ssl` and use their monkey-patching to enable this on those versions.

**Comment by VeXocide** [comment]
@larkost -- sorry for the confusion, I know a user can't currently disable `check_hostname`, I was arguing that it might be a nice feature to have. If so it should be on by default if the system supports it.

I'm fine with option 3 by the way.

**Comment by danielmewes** [comment]
@larkost I agree with your assessment. I think option 3 is the most reasonable compromise we can pick here.

There's a fourth option as well, that is a bit more conservative: We add a way for the user to disable `check_hostname`, and I agree with @VeXocide that this would be useful in general. Then if `SSLContext` doesn't exist and `check_hostname` is not explicitly disabled by the user, we fail and tell the user to disable the `check_hostname` option or use a newer version of Python.

I'm undecided on whether I prefer 3 or 4. I think 4 would be slightly better, but is also slightly more work.

**Comment by larkost** [comment]
I am half-way to implementing 3 right now. And I think the 4 is a step beyond that. Why don't I finish this, and then we do that under a separate bug. We would probably want to do this in the other drivers as well. @VeXocide, since you are the advocate, can you write it up?

**Comment by VeXocide** [comment]
I opened #5733, it'd be nice to have but that's all.

**Comment by larkost** [comment]
I am having some troubles testing this but initial work is in `larkost/4815-python-ssl-fix`.

**Comment by larkost** [comment]
This is in `next` with 79b93635 and `v2.3.x` with d79df259. I should note that I did not put in code to reuse `SSLContext` as I could not see a simple way of making sure that we were being called with the same certs bundle and on the same host in a reasonable manner. At some point that would be good to get in, but would probably have to distinguish `reconnect` from new `connect` calls.
