### ISSUE TITLE
Fails to build on OSX 10.11.4 due to 'openssl/ssl.h' file not found

### ISSUE THREAD

**Issue by amuino** [rethinkdb/rethinkdb#5776]
Build output:
```
    [17/422] CC build/release_clang/obj/arch/address.o
In file included from src/arch/address.cc:19:
./src/arch/io/network.hpp:8:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^
1 error generated.
make[1]: *** [build/release_clang/obj/arch/address.o] Error 1
make: *** [make] Error 2
```

I can find the `ssl.h` file in a different folder: `external/openssl_1.0.1t/ssl/ssl.h`. I also have another ssl version installed via homebrew in `/usr/local/opt/openssl/include/openssl/ssl.h`, but setting the usual environment settings did _not_ work:
```export CPPFLAGS=-I/usr/local/opt/openssl/include; export LDFLAGS=-L/usr/local/opt/openssl/lib;  make```

**Comment by AtnNn** [comment]
I ran into this bug on windows yesterday. I have a possible fix that I'll be testing (https://github.com/rethinkdb/rethinkdb/commit/535f5dd384fcca65e1f974cb633e520cd7538d39).

As a workaround, running `make build-openssl` before building rethinkdb should install the include files to the right place.

**Comment by amuino** [comment]
The workaround is not working for me on OSX… will try building on a docker container. Is Ubuntu ok? Or some other platform?

**Comment by danielmewes** [comment]
@amuino If you aren't doing so yet, can you pass `--fetch openssl` to `./configure` and then build again?

**Comment by amuino** [comment]
That made it compile past `address.o`, thanks @danielmewes!

**Comment by danielmewes** [comment]
Ok I'm going to close this.
We're aware of the general issue with finding OpenSSL on OS X (compare also https://github.com/rethinkdb/rethinkdb/issues/5754), and will try to improve our detection of this.

**Comment by jdmichaud** [comment]
For info, trying to cross-compile on raspberry leads to the same issue with on 2.3.5 with:
  
    ./configure --allow-fetch --ccache && \
    UBUNTU_RELEASE=trusty SIGN_PACKAGE=0 make build-deb
