### ISSUE TITLE
Compile fails in keys.cc: ambiguous template specialization ‘serialize<(cluster_version_t)0>’

### ISSUE THREAD

**Issue by srh** [rethinkdb/rethinkdb#2572]
On Wheezy, with gcc 4.7.2.

```
src/btree/keys.cc:205:1: error: ambiguous template specialization ‘serialize<(cluster_version_t)0>’ for ‘void serialize(write_message_t*, const key_range_t::right_bound_t&)’
In file included from ./src/btree/keys.hpp:12:0,
                 from src/btree/keys.cc:2:
./src/containers/archive/archive.hpp:136:6: error: candidates are: template<cluster_version_t W, class T> void serialize(write_message_t*, const T&)
src/btree/keys.cc:205:1: error:                 template<cluster_version_t W> void serialize(write_message_t*, const key_range_t::right_bound_t&)
src/btree/keys.cc:205:1: error: ambiguous template specialization ‘deserialize<(cluster_version_t)0>’ for ‘archive_result_t deserialize(read_stream_t*, key_range_t::right_bound_t*)’
```

Working in branch v1.13.x -> sam_2537 -> sam_2572.
