### ISSUE TITLE
commit 68454f5 at branch official/daniel_2168 introduced build regression

### ISSUE THREAD

**Issue by Aleaxander** [rethinkdb/rethinkdb#2188]
Hi @danielmewes,

Here the framework caught another build regression at your branch official/daniel_2168 by commit 68454f5("Proper shutdown handling for threaded coroutines"):

```
    [175/272] CC build/release/obj/arch/runtime/context_switching.o
src/arch/runtime/context_switching.cc: In destructor ‘threaded_stack_t::~threaded_stack_t()’:
src/arch/runtime/context_switching.cc:425:53: error: invalid static_cast from type ‘artificial_stack_context_ref_t’ to type ‘threaded_context_ref_t&’
src/arch/runtime/context_switching.cc:438:53: error: invalid static_cast from type ‘artificial_stack_context_ref_t’ to type ‘threaded_context_ref_t&’
make[1]: *** [build/release/obj/arch/runtime/context_switching.o] Error 1
make: *** [make] Error 2
```
