### ISSUE TITLE
Ubuntu 19.04 + rethinkdb - don't work together?

### ISSUE THREAD

**Issue by lautiamkok** [rethinkdb/rethinkdb#6773]
It seems that we can't install rethinkdb on ubuntu 19.04.

I tried this:

```
    source /etc/lsb-release && echo "deb https://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
    wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
    sudo apt-get update
    sudo apt-get install rethinkdb
```

But I get **no candidate issue**.

I tried to build from the source, but I get the following error in the end:

```

$ sudo make install 

[1/233] CC build/release/obj/rdb_protocol/geo/s2/s2.o
    In file included from src/rdb_protocol/geo/s2/s2.cc:197:
    ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:502:10: error: field ‘bn_’ has incomplete type ‘BIGNUM’ {aka ‘bignum_st’}
       BIGNUM bn_;
              ^~~
    In file included from /usr/include/openssl/bn.h:19,
                     from ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:103,
                     from src/rdb_protocol/geo/s2/s2.cc:197:
    /usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM’ {aka ‘struct bignum_st’}
     typedef struct bignum_st BIGNUM;
                    ^~~~~~~~~
    In file included from src/rdb_protocol/geo/s2/s2.cc:197:
    ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h: In constructor ‘geo::ExactFloat::ExactFloat()’:
    ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:562:3: error: ‘BN_init’ was not declared in this scope
       BN_init(&bn_);
       ^~~~~~~
    ./src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.h:562:3: note: suggested alternative: ‘BN_print’
       BN_init(&bn_);
       ^~~~~~~
       BN_print
    make[1]: *** [src/build.mk:392: build/release/obj/rdb_protocol/geo/s2/s2.o] Error 1
    make: *** [Makefile:53: make] Error 2
```

Any ideas?

**Comment by lautiamkok** [comment]
I have just upgraded my ubuntu to 19.10 and getting the same problem so i guess rethinkdb does not support the latest ubuntu yet.

**Comment by srh** [comment]
RethinkDB 2.3.x should build on 19.04, I'll give it a try.

And I'll see about putting up a 19.04 and 19.10 package.

**Comment by lautiamkok** [comment]
So should I build it from the Git branch below following this [guide](https://rethinkdb.com/docs/build)?

`wget https://download.rethinkdb.com/dist/rethinkdb-2.3.6.tgz`

**Comment by srh** [comment]
I guess this'll spur me into making a rethinkdb-2.3.7.tgz.  I'm not sure exactly how rethinkdb-2.3.6.tgz got generated, but I think it's out of the Ubuntu/Debian package building process.

I just tested the `next` (master) branch build on Ubuntu Eoan 19.10 and it succeeded.  I actually meant to test the 2.3.x branch.  So, I'm doing that now.  Then, after it succeeds, I'll build a 19.10 package.

I am currently building the 19.04 package as well.  It takes a few hours, because the package build uses 1 core.

If you follow the build instructions at http://samuelhughes.com/rethinkdb/build_instructions.html , I think, if you add `--fetch jemalloc` to the configure line, and maybe other appropriate `--fetch` lines if you have other software on your system, it will succeed.  I'll update the instructions for disco and eoan today.

You can get a working unofficial disco package at

https://github.com/srh/rethinkdb/releases/tag/v2.3.6.srh.1

**Comment by lautiamkok** [comment]
@srh thanks so much for being keen to sort this out. I think we will wait for the 19.10 package. Looking forward to it. Thanks!

**Comment by srh** [comment]
@lautiamkok Packages for disco and eoan are up now.

**Comment by srh** [comment]
rethinkdb-2.3.7.tgz is generated with `make dist`, unsurprisingly because it's in a directory named `dist` on the download server.  I've put one up.

**Comment by lautiamkok** [comment]
@srh wonderful. thank you very much for sorting it out :-D
