### ISSUE TITLE
"may be used uninitialized" when compiling 2.3 for Alpine

### ISSUE THREAD

**Issue by davefinster** [rethinkdb/rethinkdb#5635]
Hi All

Just attempting to compile 2.3 from source for Alpine Linux and am encountering the following:

```bash
    [173/422] CC build/release_system/obj/clustering/table_manager/multi_table_manager.o
    [174/422] CC build/release_system/obj/clustering/table_manager/table_meta_client.o
In file included from ./src/clustering/administration/servers/server_metadata.hpp:10:0,
                 from ./src/clustering/administration/tables/table_metadata.hpp:12,
                 from ./src/clustering/table_contract/contract_metadata.hpp:12,
                 from ./src/clustering/table_contract/coordinator/coordinator.hpp:6,
                 from ./src/clustering/table_manager/table_manager.hpp:5,
                 from ./src/clustering/table_manager/multi_table_manager.hpp:8,
                 from src/clustering/table_manager/multi_table_manager.cc:2:
./src/rpc/mailbox/typed.hpp: In member function 'void mailbox_t<void(a0_t, a1_t, a2_t, a3_t, a4_t, a5_t, a6_t, a7_t)>::read_impl_t::read(read_stream_t*, signal_t*) [with arg0_t = uuid_u; arg1_t = multi_table_manager_timestamp_t; arg2_t = multi_table_manager_bcard_t::status_t; arg3_t = boost::optional<table_basic_config_t>; arg4_t = boost::optional<raft_member_id_t>; arg5_t = boost::optional<raft_persistent_state_t<table_raft_state_t> >; arg6_t = boost::optional<raft_start_election_immediately_t>; arg7_t = mailbox_addr_t<void()>]':
./src/rpc/mailbox/typed.hpp:806:20: error: '*((void*)& arg6 +4)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             arg6_t arg6;
                    ^
cc1plus: all warnings being treated as errors
src/build.mk:390: recipe for target 'build/release_system/obj/clustering/table_manager/multi_table_manager.o' failed
make[1]: *** [build/release_system/obj/clustering/table_manager/multi_table_manager.o] Error 1
```

Configure was run with as below and the export was done prior to calling make.

```bash
./configure  --prefix=/usr --sysconfdir=/etc --localstatedir=/var --fetch v8  --dynamic all --with-system-malloc

export LDFLAGS="$LDFLAGS -lexecinfo"
```

Happy to supply any additional information/try anything that can be recommended

**Comment by VeXocide** [comment]
I'm sorry you ran into this @davefinster, could you please let me know what compiler you're using such that I can try to reproduce this. Had a quick glance at the related code and nothing stood out, it's hard to tell whether this is a bug or simply an overzealous compiler.

**Comment by davefinster** [comment]
Hi @VeXocide 

Configure output below:
```bash
* Detecting system configuration
Bash:                           4.3.42(1)-release
Use ccache:                     no
C++ Compiler:                   GCC 5.3.0 (/usr/bin/c++)
Host System:                    x86_64-alpine-linux-musl
Build System:                   Linux 4.1.19-boot2docker x86_64
Cross-compiling:                no
Host Operating System:          Linux
Build Architecture:             x86_64
C++11:                          ok
Precompiled web assets:         no
Protobuf compiler:              /usr/bin/protoc
python:                         python 2.7.11
Node.js package manager:        /usr/bin/npm
coffee:                         error
```

I'm just running through the compile with Clang now to test

**Comment by VeXocide** [comment]
Thank you, I'm currently building with GCC 5.3.0 to see if I can reproduce this. In the meantime you can work around this by using `make ALLOW_WARNINGS=1`, this disables the `-Werror` flag causing the compiler to fail on warnings.

**Comment by VeXocide** [comment]
Managed to reproduce this locally, I'll go fight GCC coming Monday.

**Comment by davefinster** [comment]
Great. Clang made it past that spot, completed compilation but failed on linking

```bash
    [431/440] BUILD v8_3.30.33.16
    [432/440] BUILD re2_20140111
    [433/440] LD build/release_clang/rethinkdb
./build/release_clang/obj/rdb_protocol/pseudo_time.o: In function `std::istreambuf_iterator<char, std::char_traits<char> > boost::date_time::time_input_facet<boost::posix_time::ptime, char, std::istreambuf_iterator<char, std::char_traits<char> > >::check_special_value<boost::posix_time::ptime>(std::istreambuf_iterator<char, std::char_traits<char> >&, std::istreambuf_iterator<char, std::char_traits<char> >&, boost::posix_time::ptime&, char) const':
/usr/include/boost/date_time/time_facet.hpp:1255: undefined reference to `std::ios_base::failure::failure(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
clang-3.6: error: linker command failed with exit code 1 (use -v to see invocation)
src/build.mk:334: recipe for target 'build/release_clang/rethinkdb' failed
make[1]: *** [build/release_clang/rethinkdb] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
```

**Comment by VeXocide** [comment]
You may be trying to link objects that were compiled with a different ABI, see https://gcc.gnu.org/onlinedocs/gcc-5.3.0/libstdc++/manual/manual/using_dual_abi.html for more information. If I remember correctly Clang could build using the GCC Standard Library, but it may be making assumptions regarding the ABI.

A fun little tidbit 'cause it's Saturday evening and I'm bored. In the days when the earth was still flat, back before C++11, there were two ways of optimizing `std::string`, or `std::basic_string<char, std::char_traits<char>, std::allocator<char> >` for the pedantic.

The first, which GCC used to use was reference counting, instead of copying a string they simply bumped up the reference count which was usually more efficient. It's important to note that GCC wasn't as naive as C++03 and earlier regarding threading, thus the reference count was an atomic integer. Those aren't exactly cheap, but it was cheaper than allocating a new chunk of memory and copying the string over. If you wanted to change a string it would still have to make a copy, also known as Copy on Write or CoW.

The other option is called Small String Optimization, often abbreviated to SSO, and it uses the string internals. An `std::string` generally contains three pointers, one to the beginning of the allocated buffer / string, one to the end of the string, and a last to the end of the allocated buffer. That's 24 bytes to muck around with on a modern machine, and you can store small strings in those bytes instead of allocating memory on the heap.

Then C++11 came around, which finally learned about threading, and http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2008/n2534.html in particular. This mandated safe concurrent access to strings, which in turn meant the end of reference counted strings. GCC had to change, and in doing so the ABI had to change, hence this whole mess.

**Comment by VeXocide** [comment]
The `maybe-uninitialized` error is very likely to be cause by GCC being overzealous. There's an issue here regarding `boost::optional<T>` and a similar error, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=47679, and `WebKit` has reportedly disabled the warning as well, https://bugs.webkit.org/show_bug.cgi?id=119835.

@AtnNn -- how can we detect the `-Wno-maybe-uninitialized` option and set it when present?

**Comment by VeXocide** [comment]
What's worse, according to the WebKit link the warning uses the GCC optimizer and can thus give different results based on the optimization level.

**Comment by VeXocide** [comment]
It turns out `-Wno-maybe-uninitialized` got added around GCC 4.4 thus we can simply set it when compiling with GCC.

**Comment by VeXocide** [comment]
Just ran into a new problem with GCC 5.3.
```
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc: In constructor 'geo::ExactFloat::ExactFloat(double)':
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:112:20: error: 'signbit' was not declared in this scope
   sign_ = signbit(v) ? -1 : 1;
                    ^
src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:112:20: note: suggested alternative:
In file included from src/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.cc:7:0:
/opt/local/include/gcc5/c++/cmath:682:5: note:   'std::signbit'
     signbit(_Tp __x)
     ^
make[1]: *** [build/release/obj/rdb_protocol/geo/s2/util/math/exactfloat/exactfloat.o] Error 1
make: *** [make] Error 2
```

**Comment by VeXocide** [comment]
This is probably due to me building on OS X, we have the following in place.
```
#ifndef __APPLE__
using std::signbit;
#endif
```
I'll check with @danielmewes why it's conditional on `__APPLE__` when he gets back.

**Comment by VeXocide** [comment]
Merged the `-Wno-maybe-uninitialized` fix to `next` via commit 027ce31ec895a949d9a28ab2624179ab359041c2, I'll leave this bug open to answer the above question. 

Hopefully it should now build on Linux using GCC 5.3.

**Comment by VeXocide** [comment]
Over the shoulder review by @larkost by the way.

**Comment by davefinster** [comment]
Oddly I didn't hit any additional issues once ALLOW_WARNINGS was set - the only (now) warning that I got was another occurrence of the original one that I observed.

**Comment by danielmewes** [comment]
@VeXocide Can we backport this to v2.3.x as well?

**Comment by VeXocide** [comment]
@danielmewes -- absolutely, give me a minute

**Comment by VeXocide** [comment]
I already did apparently, it's commit 49cfae5173687ad9e7ccb4f3ec60feeb1889f02f.

**Comment by danielmewes** [comment]
@VeXocide Regarding the `std::signbit` thing: I'm not sure. Did I commit that change?

**Comment by VeXocide** [comment]
@danielmewes -- yes, it's commit 478bf97d39ff02bd385c70d721288de86ff89656 with the message `Make using std::signbit conditional`, which is exactly what it does.

**Comment by VeXocide** [comment]
I just saw there's a previous commit, f4c8ec2a0ce356e5c68ed7d5fdb3c435618451ce, with the message `Using std::signbit required on Linux`. It turns out that GCC on OS X also needs it.

**Comment by danielmewes** [comment]
Ah I probably just found that it was needed on Linux, but caused an issue when compiling with Clang on Mac so I added the `__APPLE__` check. Maybe that was the wrong check. Does GCC on OS X use the same C++ standard library as Clang?

Checking for GCC or not is also not right, since the `using std::signbit` seems to be fine with Clang on Linux. We could just check for `#if defined(__APPLE__) && !defined(__GNUC__)` I suppose, though it's probably still not *exactly* what we should check for here.

**Comment by VeXocide** [comment]
I should've mentioned this, it was a GCC install from MacPorts, not quite sure what standard library it uses but I suspect the one that's shipped with GCC itself.

**Comment by VeXocide** [comment]
I ran into the `std::signbit` issue while reproducing #5926 thus I'll take care of it while we're at it.
