### ISSUE TITLE
test_runner swallows server crashes

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#5544]
On my branch `daniel_5542` which is branched off `next`, I ran the following test on a faulty server (compiled from `next` and not my branch):
```
daniel@newton:~/rethinkdb/test/rql_test$ ./test-runner polyglot/regression/5542
Warning: did not find any tests for JavaScript 0.10
Warning: did not find any tests for Ruby 1.9
Using rethinkdb binary /home/ssd3/daniel/rethinkdb/build/debug_clang/rethinkdb
    Python 2.6 interpreter: /usr/local/bin/python2.6, driver: /home/ssd3/daniel/rethinkdb/build/drivers/python/rethinkdb
== Starting: polyglot/regression/5542.py2.6 (T+ 0.4 sec)
./test-runner:1642: UserWarning: Worker failure: 'Server' object has no attribute 'data_path'
  warnings.warn("Worker failure: %s" % unicode(e))

== Successfully passed the 1 test in 4.31 seconds!
```

This test crashed the server as expected, but you can see that `test-runner` still reports the test as "Successfully passed".

**Comment by larkost** [comment]
This should be fixed in `next` with a7d4cb5f, and in `n2.2.x` with 34bda449.

**Comment by larkost** [comment]
Not that this was introduced in bdf85489. That made all access to the running server go though a proxy to hide when we have external servers vs. ones we spin up ourselves. This problem was a missing call on that proxy. I audited all access and the proxy should now have all of the calls used.
