### ISSUE TITLE
Build error on MacOS in src/rdb_protocol/datum.cc

### ISSUE THREAD

**Issue by larkost** [rethinkdb/rethinkdb#2739]
I am getting a build error on MacOS on `next` while building `src/rdb_protocol/datum.cc`. I am not seeing this on newton. I am building with `DEBUG=1`.
`git bisect` has narrowed the first bad build to `1cdfb5e2332795012136da32fb7a9fcb591414f9` "Moved Datum and cJSON constructors outside of datum_t, into to_datum functions.",  so pinging @srh.

The exact message is:

```
src/rdb_protocol/datum.cc:36:17: error: expected unqualified-id
    rcheck(std::isfinite(r_num), base_exc_t::GENERIC,
                ^
/usr/include/math.h:169:7: note: expanded from macro 'isfinite'
    ( sizeof(x) == sizeof(float)  ? __inline_isfinitef((float)(x))       \
      ^
./src/rdb_protocol/error.hpp:127:59: note: expanded from macro 'rcheck'
#define rcheck(pred, type, msg) rcheck_target(this, type, pred, msg)
                                                          ^
./src/rdb_protocol/error.hpp:93:10: note: expanded from macro 'rcheck_target'
        (pred)                                                       \
         ^
```
