### ISSUE TITLE
Can't build v8_3.30.33.16-patched2

### ISSUE THREAD

**Issue by Levileadermc** [rethinkdb/rethinkdb#6591]
When I'm running `make install` it errors out, I have attached the error.
[v8_3.30.33.16-patched2_install.log](https://github.com/rethinkdb/rethinkdb/files/1628313/v8_3.30.33.16-patched2_install.log)

**Comment by lbguilherme** [comment]
This log does not seem to include any error message. Are you sure this is complete? What is the error you saw?

**Comment by Levileadermc** [comment]
I got some support on the slack workspace, I'm compiling it right now
If it fails I will come back

**Comment by Levileadermc** [comment]
Also, I can't install GCC++
`The following packages have unmet dependencies:
 gcc-6-aarch64-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-alpha-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-arm-linux-gnueabi : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-arm-linux-gnueabihf : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-hppa-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-m68k-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-mips-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-mips64-linux-gnuabi64 : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-mips64el-linux-gnuabi64 : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-mipsel-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-powerpc-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-powerpc-linux-gnuspe : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-powerpc64-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-powerpc64le-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-s390x-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-sh4-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-6-sparc64-linux-gnu : Conflicts: gcc-multilib but 4:6.3.0-4 is to be installed
 gcc-multilib : Conflicts: gcc-6-aarch64-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-alpha-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-arm-linux-gnueabi but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-arm-linux-gnueabihf but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-hppa-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-m68k-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-mips-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-mips64-linux-gnuabi64 but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-mips64el-linux-gnuabi64 but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-mipsel-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-powerpc-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-powerpc-linux-gnuspe but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-powerpc64-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-powerpc64le-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-s390x-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-sh4-linux-gnu but 6.3.0-18cross1 is to be installed
                Conflicts: gcc-6-sparc64-linux-gnu but 6.3.0-18cross1 is to be installed
E: Unable to correct problems, you have held broken packages.
root@levente:~/rethinkdb-2.3.6#`

**Comment by srh** [comment]
What distro are you on?

Here are instructions that should work for v2.3.x, v2.4.x, and next. (The git branches if you clone the repo.)
https://github.com/rethinkdb/rethinkdb/issues/6389#issuecomment-350611493
A patch related to OpenSSL code got added and v2.3.6 might not build on your platform while v2.3.x might.

**Comment by Levileadermc** [comment]
@srh I use Debian, but I got the exact error
`root@levente:~/rethinkdb-2.3.6# make -j 2
    [1/1] LD build/release/rethinkdb
/usr/bin/ld: /root/rethinkdb-2.3.6/build/external/openssl_1.0.1t/lib/libssl.a(ssl_algs.o): undefined reference to symbol 'EVP_dss1@@OPENSSL_1.0.2d'
//usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/build.mk:334: recipe for target 'build/release/rethinkdb' failed
make[1]: *** [build/release/rethinkdb] Error 1
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
root@levente:~/rethinkdb-2.3.6#`

**Comment by Levileadermc** [comment]
Downloaded 2.3.x, ran the commands you wrote in #6389, got this error:

`root@levente:~/rethinkdb-2.3.x# make -j 2
./scripts/gen-version.sh: Warning: could not determine the version, using the default version '2.3.6-fallback'
./scripts/gen-version.sh: Warning: could not determine the version, using the default version '2.3.6-fallback'
    [1/446] FETCH coffee-script_1.10.0
    [2/446] BUILD bluebird_2.9.32
+ npm install /root/rethinkdb-2.3.x/external/bluebird_2.9.32
++ mktemp -d /root/rethinkdb-2.3.x/external/npm_cache-XXXXXXXX
+ cache_dir=/root/rethinkdb-2.3.x/external/npm_cache-rRIiU0b6
+ /usr/bin/npm --userconfig /root/rethinkdb-2.3.x/mk/support/config/npm.conf --cache /root/rethinkdb-2.3.x/external/npm_cache-rRIiU0b6 install /root/rethinkdb-2.3.x/external/bluebird_2.9.32
npm WARN enoent ENOENT: no such file or directory, open '/root/rethinkdb-2.3.x/build/external/bluebird_2.9.32/package.json'
npm WARN bluebird_2.9.32 No description
npm WARN bluebird_2.9.32 No repository field.
npm WARN bluebird_2.9.32 No README data
npm WARN bluebird_2.9.32 No license field.

npm ERR! path /root/rethinkdb-2.3.x/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-366a5b28
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/root/rethinkdb-2.3.x/build/external/bluebird_2.9.32/node_modules/.staging/bluebird-366a5b28' -> '/root/rethinkdb-2.3.x/external/bluebird_2.9.32/node_modules/bluebird'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/rethinkdb-2.3.x/external/npm_cache-rRIiU0b6/_logs/2018-01-15T15_38_52_750Z-debug.log

Full error log: ./build/external/bluebird_2.9.32_install.log
mk/support/build.mk:121: recipe for target 'build/external/bluebird_2.9.32/install.witness' failed
make[1]: *** [build/external/bluebird_2.9.32/install.witness] Error 1
make[1]: *** Waiting for unfinished jobs....
Makefile:52: recipe for target 'make' failed
make: *** [make] Error 2
root@levente:~/rethinkdb-2.3.x#`

**Comment by Levileadermc** [comment]
Okay, your fix helped it go further, but I stumbled upon another problem
`
    [13/425] PROTOC build/proto/rdb_protocol/ql2.pb.cc
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: rdb_protocol/ql2.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
    [14/425] BUILD jemalloc_4.1.0
    [15/425] BUILD v8_3.30.33.16
    [16/425] CP ./build/drivers/ruby/lib
    [17/425] CC build/release/obj/web_assets/web_assets.o
    [18/425] CC build/release/obj/rdb_protocol/ql2.pb.o
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* VersionDummy::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:613:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Query_AssocPair::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:907:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Query::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:1324:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Frame::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:2011:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Backtrace::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:2404:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Response::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:2946:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Datum_AssocPair::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:3592:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Datum::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:4018:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Term_AssocPair::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:5053:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
build/proto/rdb_protocol/ql2.pb.cc: In member function ‘virtual google::protobuf::uint8* Term::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
build/proto/rdb_protocol/ql2.pb.cc:5406:10: error: unused parameter ‘deterministic’ [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
src/build.mk:385: recipe for target 'build/release/obj/rdb_protocol/ql2.pb.o' failed
make[1]: *** [build/release/obj/rdb_protocol/ql2.pb.o] Error 1
make[1]: *** Waiting for unfinished jobs....
`

**Comment by srh** [comment]
That's weird because -Werror should not be activated by default.

**Comment by Levileadermc** [comment]
Aaaaand how can I disable that?

**Comment by srh** [comment]
Probably one of the uses of `-Werror` in the directory external/openssl_1.0.1t is the culprit.

**Comment by Levileadermc** [comment]
Okay, ran it with `VERBOSE=1`
Output: https://gist.github.com/Levileadermc/8beae2777279afc6e495384c982d63fe

**Comment by srh** [comment]
If you build version 2.3.5 you'll have to pass ALLOW_WARNINGS=1.

**Comment by Levileadermc** [comment]
Compiled with `ALLOW_WARNINGS=1`
Error, Output: https://gist.github.com/Levileadermc/f4d39ac3c44b20a535c762c7cffb3877

**Comment by srh** [comment]
Because you're building 2.3.5 you have errors building on Stretch. 2.3.6 won't work either. If you want to build on Stretch you need to use the v2.3.x branch.
